### ISSUE TITLE
Error in notifier.loop()

### ISSUE THREAD

**Issue by Variables00** [zzbe/mikrocata#2]
Hello, I really appreciated your work. But there is a issue, every 3 seconds the python script fails, with this kind of error. 
```
File "mikrocata.py", line 349, in
notifier.loop()
File "/usr/local/lib/python3.6/site-packages/pyinotify.py", line 1376, in loop
self.process_events()
File "/usr/local/lib/python3.6/site-packages/pyinotify.py", line 1275, in process_events
self._default_proc_fun(revent)
File "/usr/local/lib/python3.6/site-packages/pyinotify.py", line 910, in call
return _ProcessEvent.call(self, event)
File "/usr/local/lib/python3.6/site-packages/pyinotify.py", line 630, in call
return meth(event)
File "mikrocata.py", line 67, in process_IN_MODIFY
add_to_tik(read_json(FILEPATH))
File "mikrocata.py", line 126, in add_to_tik
for event in {item['src_ip']: item for item in alerts}.values():
File "mikrocata.py", line 126, in
for event in {item['src_ip']: item for item in alerts}.values():
KeyError: 'src_ip'
```
Can you help me? Please!
Thanks for your working!

**Comment by zzbe** [comment]
Hey I'll try but this is my beginner script:) Did you add alerts.json to suricata.conf - do you have alerts.json file with alerts in it? Problem seems to be with Key 'src ip'.

**Comment by Variables00** [comment]
Yep I have added it, but I think the error is in the parsing of the values. With which version of Suricata do you have tested it?

**Comment by zzbe** [comment]
I have v5.0.3. Can you check your alerts.json entries; my script assumes 'src_ip' is in every entry. That line of code checks src_ip of every entry and removes any duplicates. My guess is src_ip is missing in some entries?

**Comment by Variables00** [comment]
Okay, I have resolved the issue. You're right: src_ip and Alert message was missing in some entries. I have updated Suricata and reconfigured all the settings in the .yaml. Now works perfectly.

Thank U Boy!
