### ISSUE TITLE
script does not start

### ISSUE THREAD

**Issue by Unix-MTv** [zzbe/mikrocata#3]
```
# pip install librouteros ujson pyinotify or apt install python-librouteros python-ujson python-pyinotify
# python3 mikrocata.py
Traceback (most recent call last):
File "mikrocata.py", line 26, in <module>
from librouteros.query import Key
ModuleNotFoundError: No module named 'librouteros.query'
```
Requirements installed. OS Debian Buster.
Please write a mini instruction.

**Comment by Unix-MTv** [comment]
if you comment out "#from librouteros.query import Key", then the error takes off:
```
# python3 mikrocata.py
[Mikrocata] File: /etc/mikrocata/ignore.conf not found. Continuing..
Traceback (most recent call last):
  File "mikrocata.py", line 331, in main
    notifier.loop()
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 1376, in loop
    self.process_events()
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 1275, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 910, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 630, in __call__
    return meth(event)
  File "mikrocata.py", line 73, in process_IN_MODIFY
    add_to_tik(read_json(FILEPATH))
  File "mikrocata.py", line 125, in add_to_tik
    _address = Key("address")
NameError: name 'Key' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mikrocata.py", line 348, in <module>
    main()
  File "mikrocata.py", line 333, in main
    except (librouteros.exceptions.ConnectionClosed, socket.timeout) as e:
AttributeError: module 'librouteros.exceptions' has no attribute 'ConnectionClosed'
```

**Comment by zzbe** [comment]
Are you sure you installed python-librouteros? Because it looks like it can't find it. Dont know if package is available in Debian repos, but here is github: https://github.com/luqasz/librouteros

**Comment by Unix-MTv** [comment]
This package is installed..
```
# apt search python3-librouteros
python3-librouteros/stable 2.2.0-1 all
Python implementation of RouterOS API
```
What version of the package and distribution do you have?

**Comment by zzbe** [comment]
3.0.1, ArchlinuxARM. Works on Manjaro as well (same version).

**Comment by Unix-MTv** [comment]
OK. There are no such errors on version 3.0.1.

But what about Loop Errors?
```
[Mikrocata] (8) KeyError: 'alert'
[Mikrocata] (8) KeyError: 'src_ip'
```

**Comment by zzbe** [comment]
Did you make another entry in suricata.yaml for alerts.json?

```
  - eve-log:
      enabled: yes
      filetype: regular
      filename: alerts.json
      types:
        - alert
```
There should be only alerts in that file (alerts.json), so each entry should have alert and src_ip key. But in your case it seems some entries aren't alerts.

**Comment by Unix-MTv** [comment]
Yes, this is my carelessness. The alerts.json file is currently empty.
Another "- eve-log:" added.
Changed af-packet: - interface: to the required one. Understood a little. It remains to defeat alerts.json - so far empty. What other parameters of suricata.yml need to be edited?

**Comment by zzbe** [comment]
I think that's the only edited thing besides HOME_NET: "[my_lan_network1/24, lan_network2/24]".
You can also check your eve.json file or fast.log. Is Suricata getting anything logged at all? Are there any 'alert' entries? What is your setup with Suricata? Which Suricata version are you using (mikrocata is tested with >= 5.0.3 but this isn't the problem here)?

**Comment by Unix-MTv** [comment]
Really. I had to wait long enough for "" event_type ":" alert "" to appear in the alerts.json file. And events of this type will be events for protection. Or is it better to block other events as well?

**Comment by zzbe** [comment]
Afaik other events are informational; like flows etc and this script is specifically made to only check for alerts. You can add your own alerts though and/or you can add different lists with suricata-update. So I can mark this as solved? I only have one last question for you; how long apart do you have alerts now? (Asking because my script is relying on having at least one alert every 15 minutes, might need to rewrite that part)

**Comment by Unix-MTv** [comment]
Could you please refine your question?
```
For debian10:
# apt install python3-pip
# pip3 install librouteros ujson pyinotify
```
By the way, everything is currently running on Debian 10. Suricata is compiled.
There is already an instruction in the draft. As soon as I transfer it to my site, I will let you know.

**Comment by zzbe** [comment]
You said you had to wait long time before there was any alert in alerts.json. I'm just curious how apart, on average, these alerts are on your PC - one every 5 minutes? every 30 minutes? I'm glad everything is working. =)

**Comment by Unix-MTv** [comment]
You know. Measured the speed at speedtest. As soon as the download speed began to be shown, I flew an alert to ROS. Those. almost instantly when an event occurs in alerts.json. And they are spaced in time - [so](https://i114.fastpic.ru/big/2020/1021/e0/31249456a3b191e5d2d254806f9307e0.png).

**Comment by zzbe** [comment]
Ok, thanks for info. Btw, there are a lot of annoying rules in suricata, so read their documentation if you need to disable any of them. (there is disabled.conf file for example). It's important you monitor alerts in the beginning because there will be some perfectly fine traffic blocked.

**Comment by Unix-MTv** [comment]
I noticed. Thanks for the information! I will also observe and optimize =)

**Comment by Unix-MTv** [comment]
Installation [FAQ](https://open-networks.ru/d/89-mikrotik-nastroyka-idsips-suricata-v-svyazke-s-ros-mikrocata) for Debian Buster =)

**Comment by zzbe** [comment]
Oh, great! =) This week I'll refresh this a bit - I'm not using port mirroring anymore, but I use TZSP packets in mangle. And then tzsp2pcap and tcpreplay on dummy network and then Suricata listens on this dummy network. So you can send whichever mikrotik port/interface and how many you want to tzsp2pcap.

**Comment by Unix-MTv** [comment]
Thanks! Well, yes, the main disadvantage of port mirror is that you can only select one port src and one port dst. But the plus is that there is no load on the Mikrotik CPU, only on the built-in Switch Chip. I heard about TZSP packets in mangle, but what about the stability? Doesn't it happen that traffic suddenly stops being transmitted?

**Comment by zzbe** [comment]
So far it works great. It even spams Suricata/Mikrocata less because when IP is blocked there is no more packets reaching mangle (when port-mirroring you can constantly get alerts from same IP - and re-adding them to blocklist).

Btw I see on your page "add action=drop chain=prerouting comment="Drop IDPS" in-interface=FTTx src-address-list=suricata_alert" -- so you probably need to tell that you need to change BLOCK_LIST_NAME = "Suricata" to "suricata_alert". 

Anyway, hopefully this week I'll manage to add all the info how to make it work with TZSP.

**Comment by Unix-MTv** [comment]
That's cool!

Well, yes, without editing this variable "BLOCK_LIST_NAME", it won't work =)

Of course, it will come in handy and will be useful to familiarize yourself!

**Comment by zzbe** [comment]
Hey, I managed to upload newer version + TZSP sniffing instructions. You can check it out, I think its better than mirroring. I hope I didn't forget anything + that I explained everything half decent. =)

**Comment by Unix-MTv** [comment]
Yo, Great! I'll try. I will write about the result. I think closer to the weekend..

**Comment by Unix-MTv** [comment]
Hey. Following your TZSP instructions, it worked out! Thanks! So far, I have only noticed more RAM consumption and new alerts that suricata did not find before. I will add to my mini-instruction the setting according to your method =)

Still wondering, is port scan detection working for you? I tried it on Android using the IP Tools program. For now, I get by with the built-in ROS - PSD.

Are you getting enough of TZSP sniffing in the prerouting chain? Or what chains should you send to Suricata ..

**Comment by zzbe** [comment]
Nice to hear it's working. I didn't notice any different ram usage tbh, not by much at least. tzsp2pcap and tcpreplay add a bit but nothing problematic. As for microcata I only changed how it deals with Mikrotik uptime and re-adding rules on reboot. Now it saves uptime to /var/lib/mikrocata/uptime.bookmark.

I don't even know, is there port scan detection in Suricata? Will need to check online now. Is there any specific rule for it somewhere? I have pretty aggressive rule in /ip firewall filter for tcp scans anyway. (add action=add-src-to-address-list address-list=Port-scanners address-list-timeout=2w chain=portscan comment="Port scan limit reached" log=yes log-prefix="Limit reached " protocol=tcp psd=9,5s,3,1)

Well I send everything in mangle prerouting to Suricata, so thats basically everything that passes through router except for output I guess. (input + forward traffic ~= traffic in that mangle roule) You can only select ether1 if you want. You can have multiple mangle rules - to pick and choose what you want to inspect. Thats the reason I prefer this way.

**Comment by Unix-MTv** [comment]
I meant memory consumption on the MikroTik device itself. When a port scan was performed, did Suricata detect it using ET Scan rules? I agree, you can direct traffic more hypocritically. Is this file created by itself? /var/lib/mikrocata/uptime.bookmark

**Comment by zzbe** [comment]
Yes, common SQL ports were detected, and OS Probe as well - whatever they have in rules. Test it yourself with nmap. Yes, savelists and uptime files are both created automatically (unless script is run as a user without privileges).
