### ISSUE TITLE
ignore conf

### ISSUE THREAD

**Issue by RabotegT** [zzbe/mikrocata#5]
Hi, i have just managed to get it working.
Great job!

have one question about White list (ignore.conf).
Can you write an example in the file..

I would like to to somthing like this:

pass ip 1.2.3.4 any <> any any (msg:"pass all traffic from/to 1.2.3.4"; sid:1000001;)

I guess I could put that in suricata local.rules..

**Comment by zzbe** [comment]
Hey. If you open ignored.conf in [repo](https://github.com/zzbe/mikrocata/blob/master/ignore.conf) you will see syntax.
I made it to ignore rules like your example - if you put your example sid in there '1000001' or regex  're:pass all traffic.*1.2.3.4' it will ignore that rule.

But Suricata also has /etc/suricata/disabled.conf for exactly this (and it's probably more efficient to disable rules there), so don't know why I made it. :D 

You definitely *should* put your rule into local.rules.

**Comment by RabotegT** [comment]
Wow thanx for prompt reply.. Will do that..
Need to fine tune the suricata a little.. To many false positives

**Comment by zzbe** [comment]
Yeah, that's exactly why Suricata has disable.conf. Check their docs for syntax.

Here is part of mine:
```
cat /etc/suricata/disable.conf 
# SURICATA STREAM rules
group:stream-events.rules
group:app-layer-events.rules
re:SURICATA.*invalid checksum
2200035  # TCP invalid option length
2230010  # TLS rules  
2200036  # -//-
2230003  # -//-
```
